run:
  build-tags:
    - integration

linters:
  enable:
    - revive
    - unconvert
    - goconst
    - misspell
    - prealloc
    - gocritic
    - govet
    - deadcode
    - gci
    - importas
    - goimports
    - gofmt

linters-settings:
  errcheck:
    # report about not checking of errors in type assertions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: true

  govet:
    # report about shadowed variables
    check-shadowing: true
