version: '3'

services:
  starter:
    image: dadarek/wait-for-dependencies:latest
    command: localstack:4566
    environment:
      - SLEEP_LENGTH=5
      - TIMEOUT_LENGTH=300
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:0.13.1
    ports:
      - "4566-4599:4566-4599"
      - "8080:${PORT_WEB_UI-8080}"
    environment:
      HOSTNAME: localstack
      HOSTNAME_EXTERNAL: localstack
      SERVICES: dynamodb,kms,s3,sqs,kinesis
      DEFAULT_REGION: us-east-1
    healthcheck:
      test: nc -z localhost 4566
      interval: 5s
      timeout: 1s
      retries: 10
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack:/tmp/localstack"

volumes:
  localstack:
