name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  GO_VERSION: '1.20'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install tools
        run: make install-tools
      - name: Lint
        run: make ci-lint

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Set up environment
        run: make up-daemon
      - name: Run integration tests
        run: make ci-test
